/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConvertButton: typeof import('./src/components/ConvertButton.vue')['default']
    FrameworkSelector: typeof import('./src/components/FrameworkSelector.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextareaCustom: typeof import('./src/components/TextareaCustom.vue')['default']
  }
}
